spring.application.name=employeeManagement
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,metrics,prometheus


# HikariCP Connection Pool Settings
# 1. Pool Sizing
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=20

# 2. Timeouts (in milliseconds)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# 3. Connection Health & Performance
spring.datasource.hikari.pool-name=SpringBootHikariPool
spring.datasource.hikari.keepalive-time=30000